[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xdc9656"
index = 16

[[colors.indexed_colors]]
color = "0xa16946"
index = 17

[[colors.indexed_colors]]
color = "0x282828"
index = 18

[[colors.indexed_colors]]
color = "0x383838"
index = 19

[[colors.indexed_colors]]
color = "0xb8b8b8"
index = 20

[[colors.indexed_colors]]
color = "0xe8e8e8"
index = 21

[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x000000"
foreground = "0xfbf1c7"

[colors.selection]
background = "0xdc3232"
text = "0xffffff"

[cursor.style]
blinking = "off"
shape = "Beam"

[font]
size = 7.5

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
opacity = 1

[window.dimensions]
columns = 140
lines = 36

[window.padding]
x = 25
y = 20
